### PR TITLE
Properly color Nautilus and FileChooser sidebar, improve inactive tabs readability

### PR DESCRIPTION
**Pull request by riesinger**
I fixed the Nautilus and GtkFileChooser sidebar background being white with the dark theme applied.
I also adjusted the font color of inactive entries in the sidebars to make them slightly more readable.

More readability fixes to come!

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@Arial7 Can you apply it for normal `gtk` theme?
Also you can add this other fix: https://github.com/xenlism/minimalism/issues/3#issuecomment-166590063

**Comment by riesinger** [comment]
@SalahAdDin I do not use minimalism anymore (it has almost been two years...), So probably not. Sorry 😅

**Comment by SalahAdDin** [comment]
@riesinger  So, what do you use now?

**Comment by xenlism** [comment]
Closed

**Comment by SalahAdDin** [comment]
@xenlism Why?

**Comment by xenlism** [comment]
I will fix ASAP.

**Comment by SalahAdDin** [comment]
@xenlism Thank you.

**Pull request closed without merging**
